name: Deploy to AWS

on:
  push:
    branches:
      - feat/integrate-aws-host

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 📂 Configurar acceso SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws_key.pem
          chmod 400 ~/.ssh/aws_key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Desplegar en AWS
        run: |
          ssh -i ~/.ssh/aws_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /ruta/del/proyecto
            git pull origin main
            npm install  # O el comando que necesites
            pm2 restart app  # Si usas PM2 para correr el servidor
          EOF

